# job needs 1 compute node with 1 processor per node.
#PBS -l nodes=1:ppn=1,pmem=20gb,pvmem=22gb
# It should be allowed to run for up to 2 hours
#PBS -l walltime=02:00:00
# Name of job.
#PBS -N chimera_0.22222_0.09091_1
# Join STDERR TO STDOUT.
#PBS -j oe
# Email me upon failure
#PBS -M hmmitche@uvm.edu
#PBS -m a

cd $HOME/thesis/code/python
$HOME/pyenv/bin/python run.py 0.22222 0.09091 -f /users/h/m/hmmitche/thesis/data/shanahan.csv -n 1
