# job needs 1 compute node with 1 processor per node.
#PBS -l nodes=1:ppn=1,pmem=20gb,pvmem=22gb
# It should be allowed to run for up to 2 hours
#PBS -l walltime=02:00:00
# Name of job.
#PBS -N chimera_0.90000_0.90000
# Join STDERR TO STDOUT.
#PBS -j oe
# Email me upon failure
#PBS -M hmmitche@uvm.edu
#PBS -m a

cd $HOME/thesis/code/python
$HOME/pyenv/bin/python run.py 0.90000 0.90000 -d /users/h/m/hmmitche/thesis/data/high_res/
